### ISSUE TITLE
avers being suspended from stackage nightly

### ISSUE THREAD

**Issue by cdornan** [wereHamster/avers#1]
`avers` is blocking `inflections-4.0.0.0`, which we need as `inflections-3.0.0.0` was blocking megaparsec-6, which has been held up for 4 weeks (see https://github.com/fpco/stackage/issues/2666).

Can you get avers to work with `inflections-4.0.0.0` so we can get `avers` back into stackage nightly.

**Comment by wereHamster** [comment]
Would it be possible to get notified about these transitive dependencies earlier? I don't think allowing inflections 0.4 is going to be much work (in fact, I think I can just bump the upper bounds on hackage, since the megaparsec API doesn't leak through the inflections package in any meaningful way). You could avoid all this churn of dropping avers and then including it again a few hours later if you notified me about this earlier (ideally the same day fpco/stackage#2666 was created).

**Comment by wereHamster** [comment]
All tests pass. I updated the upper bounds on hackage.

**Comment by cdornan** [comment]
@wereHamster that is a very good question! I have just come in and don't know how obvious it was to see this with our current tools, but I certainly agree with you and would happily notify you ahead of time instead of this.

But I am in charge until Monday and will hook it back in for the next run.

**Comment by cdornan** [comment]
I have a [stackage PR](https://github.com/fpco/stackage/pull/2798) to reinstate avers on nightly which I will merge before the next run.

**Comment by juhp** [comment]
I guess this could be closed
